program('2dfir').
program('adpcm').
program('aha-compress').
program('aha-mont64').
program('blowfish').
program('bs').
program('bubblesort').
program('cnt').
program('compress').
program('cover').
program('crc').
program('crc32').
program('ctl-stack').
program('ctl-string').
program('ctl-vector').
program('cubic').
program('dijkstra').
program('dtoa').
program('duff').
program('edn').
program('expint').
program('fac').
program('fasta').
program('fdct').
program('fft').
program('fibcall').
program('fir').
program('frac').
program('insertsort').
program('janne_complex').
program('jfdctint').
program('lcdnum').
program('levenshtein').
program('lms').
program('ludcmp').
program('matmult-float').
program('matmult-int').
program('mergesort').
program('minver').
program('nbody').
program('ndes').
program('nettle-arcfour').
program('nettle-cast128').
program('nettle-des').
program('nettle-md5').
program('newlib-exp').
program('newlib-log').
program('newlib-mod').
program('newlib-sqrt').
program('ns').
program('nsichneu').
program('picojpeg').
program('prime').
program('qrduino').
program('qsort').
program('qurt').
program('recursion').
program('rijndael').
program('select').
program('sglib-arraybinsearch').
program('sglib-arrayheapsort').
program('sglib-arrayquicksort').
program('sglib-dllist').
program('sglib-hashtable').
program('sglib-listinsertsort').
program('sglib-listsort').
program('sglib-queue').
program('sglib-rbtree').
program('sha').
program('slre').
program('sqrt').
program('st').
program('statemate').
program('stb_perlin').
program('stringsearch1').
program('strstr').
program('tarai').
program('trio-snprintf').
program('trio-sscanf').
program('ud').
program('whetstone').

